export const testimonials = [
    {
        testimonial_id: 7412,
        name: "John Doe",
        img_url: "",
        address: "123 Main Street, Cityville",
        rating: 5,
        message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin eget justo sit amet risus finibus gravida.",
    },
    {
        testimonial_id: 5486,
        name: "Jane Smith",
        img_url: "",
        address: "456 Oak Avenue, Townsville",
        rating: 4,
        message: "Sed quis metus ut odio dictum cursus vel ac leo. Suspendisse ac massa id leo tristique pharetra.",
    },
    {
        testimonial_id: 9123,
        name: "Sam Johnson",
        img_url: "",
        address: "789 Pine Road, Villageland",
        rating: 5,
        message: "Vivamus non arcu at elit tincidunt varius a et erat. Sed nec mi vel felis commodo mattis.",
    },
    {
        testimonial_id: 4567,
        name: "Emily White",
        img_url: "",
        address: "101 Cedar Street, Hamletville",
        rating: 4,
        message: "Curabitur ac mi vel tellus luctus ultrices. Nullam id nisi a lectus ullamcorper accumsan.",
    },
    {
        testimonial_id: 8921,
        name: "Alex Turner",
        img_url: "",
        address: "202 Elm Lane, Boroughburg",
        rating: 5,
        message: "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
    },
    {
        testimonial_id: 3654,
        name: "Olivia Brown",
        img_url: "",
        address: "303 Walnut Drive, Township",
        rating: 4,
        message: "Aenean rhoncus justo at tortor semper, et accumsan sapien bibendum. Sed ullamcorper turpis nec sapien auctor, non fringilla odio rhoncus.",
    },
    {
        testimonial_id: 2187,
        name: "Chris Miller",
        img_url: "",
        address: "404 Birch Street, District",
        rating: 5,
        message: "In hac habitasse platea dictumst. Quisque ut ultrices odio, nec varius purus. Nunc at massa eget urna vestibulum hendrerit.",
    },
];
